name: Fast API docker build push
on:
   push:
     branches: [ master ]  

jobs: 
   build:
       runs-on: ubuntu-latest
       steps:
         - uses: actions/checkout@v3 
         - name : Build docker image for FastAPI
           run: docker build -t '${{screts.DOCKER_USERNAME}}'/fastapi-docker:'${{github.sha}}' .


           -name: logging to the docker hub
           run : docker login --username '${{screts.DOCKER_USERNAME}}' --paswword '${{secrets.Docker_Password}}'

           -name: Push the image to the docker hub
             run:  docker push '${{screts.Docker_USERNAME}}'/fastapi-docker:'${{github.sha}}'