name: FastAPI Docker Build and Push

on:
  push:
    branches: [ main ]

jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3 

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "vanshika002" --password-stdin

      - name: Build Docker image for FastAPI
        run: docker build -t "vanshika002/testing_docker_fastapi:${{ github.sha }}" .

      - name: Push the image to Docker Hub
        run: docker push "vanshika002/testing_docker_fastapi:${{ github.sha }}"
