name: Fast API docker build push

on:
  push:
    branches: [ master ]

jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 

      - name: Build docker image for FastAPI
        run: docker build -t '${{secrets.Vanshika002}}'/fastapi-docker:'${{github.sha}}' .

      - name: Logging into Docker Hub
        run: docker login --username '${{secrets.Vanshika002}}' --password '${{secrets.vanshika@1920}}'

      - name: Push the image to Docker Hub
        run: docker push '${{secrets.Vanshika002}}'/fastapi-docker:'${{github.sha}}'
