name: Docker image build

on: push
    


jobs:
    build:

        runs-on: ubuntu-latest

        steps: 



	-


	-
              run: |
                echo ${{ secrets.DOCKERTOKEN }} | docker login -u "vanshika002" --password-stdin
                docker build -t dockerhub_username/dockerhub_image_name:v0.1 .
                docker push dockerhub_username/dockerhub_image_name:v0.1

